### ISSUE TITLE
Update NIDM-Primer Overview Figure

### ISSUE THREAD

**Issue by nicholsn** [incf-nidash/nidm#102]
In PR #74 @satra raised the point that the NIDM overview figure could be updated to be more accurate, particularly how the API is situated. This issue is to keep track of the need for more discussion about the figure, while allowing the specification PR to be merged.

Please feel free to post your comments and suggestions here.

**Comment by cmaumet** [comment]
@nicholsn: do you know if we have an editable version of the layer cake image somewhere in our shared folders? I have looked for it but could not find it... Thanks!

**Comment by nicholsn** [comment]
@cmaumet, there is and it is the more recent one than what is on the website.... never updated it :-/

You should be able to access it [here](https://www.lucidchart.com/documents/edit/669c1f76-96d9-433d-9b51-378e7ca5b24a)

**Comment by cmaumet** [comment]
Thank you @nicholsn!

**Comment by cmaumet** [comment]
I will close this issue now. The layer diagram is now used up to level 3. Feel free to reopen this issue if you think we should discuss this further. Thanks!
