### ISSUE TITLE
Definition of "spm:maximumIntensityProjection"

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#129]
This discussion was initiated as a [comment on the spreadsheet of terms](https://docs.google.com/spreadsheets/d/16pC2cDsdxlzv2CzlNMtStqt5-xHwDEsU6MjZVxWhrE4/edit?disco=AAAAAGsZF9Y).

---
**Term**: `spm:maximumIntensityProjection`
**Current definition**: Maximum intensity projection of a map.
**Link**:  [nidm-results.owl/maximumIntensityProjection](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/nidm-results.owl#L918-L929)

---

@khelm `19:43 9 Apr`
_Selected text: "Maximum intensity projection of a map."_
"A map in which each element represents the maximum element value over a specified number of elements along a certain dimension ."

@nicholsn `20:00 18 Apr`
+1, but might add that this is "A map attribute.."

[side discussion on Domain/Range between @cmaumet and @nicholsn, not reported here]

@gllmflndn `10:38 12 May`
This term corresponds specifically to `nidm:visualisation` of `nidm:ExcursionSet`.

**Comment by nicholst** [comment]
We'll close this as this is now under discussion in #293.
