### ISSUE TITLE
Re-using terms from STATO: synonyms or direct re-use?

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#136]
Since #120, we are re-using terms from the statistics ontology [STATO](http://stato-ontology.org/) (cf. STATO on [BioPortal](http://bioportal.bioontology.org/ontologies/STATO) and [Github](https://github.com/ISA-tools/stato)) as part of NIDM.

Examples of such terms are "T-Statistic" and "one-tailed test".

For each re-used term, an alias was created in the `nidm` namespace and a `rdfs:sameAs` relationship was used to link to STATO definition (for an example see TStatistic in nidm-results.owl).

Another solution would have been to re-use directly the STATO terms (as we did for PROV terms and relations). A potential issue with this second approach is that STATO seems to use alphanumerical identifiers while we used human-readable identifiers in NIDM.

I am not sure about the implication of using one or the other solution and I thought it would be worth starting a discussion to see if you have opinions or advice on this.

Thank you in advance

**Comment by nicholst** [comment]
Alpha-numeric identifiers are almost here; see #296.  We now have also resolved to reuse as many STATO terms as possible; see e.g. #262.  So we'll close this again now.
