### ISSUE TITLE
Recommended naming of NIDM-Results directories and compression for transfer

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidm#151]
Following conversations with @chrisfilo, @jbpoline, @gllmflndn & @cmaumet we have decided to recommend that NIDM results directories be named with a `.nidm` extension.  The recommended way to transfer these files is as a zipped directory, resulting in a `.nidm.zip` extension.

Further, the serialisation inside the directory is recommended to be named `nidm.ttl` (or `nidm.provn` or whichever format used).

These decisions are made to make it easier for developers who will accept NIDM serialisation+data.

It noted that @chrisfilo feels that it would be better if we instead defined the NIDM transfer format **as** the zipped directory, i.e. so that the `blah.nidm` would be a file that is *actually* a zipped file (much like .docx files are actually zipped directories).  He accepted that @satra would hate this, and so gave up on it.

**Comment by cmaumet** [comment]
This was discussed on NIDM call on Nov 2nd 2015.
