### ISSUE TITLE
Definition of "MaskMap"

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#155]
**Term**: `MaskMap `
**Current definition**: "A map whose value at each location denotes whether the element is of interest for further analysis."
**Original comment**: [link](https://docs.google.com/a/mrn.org/spreadsheets/d/16pC2cDsdxlzv2CzlNMtStqt5-xHwDEsU6MjZVxWhrE4/edit?disco=AAAAAGsYjiI)

---

@khelm `20:26 9 Apr`
This seems overly restrictive. How about: "A matrix whose function is to select a subset of elements in an image or parameter map."? Here it would just be "parameter map".
	
@nicholsn `21:16 18 Apr`
+1
	
@JessicaTurner `20:49 22 Apr`
Are we defining a mask by what it does or how it's built? I think of it as being 1s and 0s as well as being applied to actually mask voxels in or out. But if that's too restrictive...
	
@cmaumet `16:56 23 Apr`
Following Karl and relying on the definition of 'Map' we could have:
"A binary map whose function is to select a subset of elements."

**Comment by cmaumet** [comment]
@JessicaTurner, @khelm, @nicholst: how about:

**MaskMap**: "A binary map in which selected elements (e.g., pixels, voxels, vertices, and faces) have a value of 1 and excluded elements have a value of 0 or NaN."

I think that removing "function" is a bit clearer as a `MaskMap` can be input or output of an Activity.  Adding examples of "elements" might help understanding what we mean (i.e. voxels in a 3D volumetric map).

**Comment by khelm** [comment]
I agree about "function" being problematic if it's an output.  So +1 for the @cmaumet definition.

**Comment by cmaumet** [comment]
I will now close this issue as the definition of **nidm:MaskMap** was discussed and agreed upon in #258.
