### ISSUE TITLE
NIDM-experiment spec: UML chart is truncated

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#249]
As noted by @nicholst in #245, the UML chart is truncated in the right in the NIDM-experiment specification.

**Comment by cmaumet** [comment]
@nicholsn: It looks like you have been working on an updated version of the nidm-experiment UML chart, would you like to update the spec accordingly?

**Comment by nicholsn** [comment]
Sure, I'll try to get this done before the call on monday.

sent via mobile, please excuse brevity and typos

**Comment by nicholsn** [comment]
[Link to current figure](https://drive.google.com/open?id=0B-BLof5_SOh8NGJWeklpLUJPdE0&authuser=0)

**Comment by nicholsn** [comment]
@cmaumet, do you have any instructions on how to generate the spec from the owl file?

**Comment by cmaumet** [comment]
@nicholsn: you can use:
`python nidm/nidm-experiment/scripts/create_expe_specification.py`

**Comment by nicholsn** [comment]
hmm... im getting the following... thoughts?

```
python nidm/nidm-experiment/scripts/create_expe_specification.py
/Users/nolan/Repos/nidm/scripts/OwlReader.py:90: UserWarning: No PROV type for class: nidm:TaskBasedImagingAcquisition
  warnings.warn('No PROV type for class: '+self.graph.qname(class_name))
```

**Comment by cmaumet** [comment]
Hi @nicholsn.  This is just a warning but the html should have been generated properly. Can you check it?

**Comment by nicholst** [comment]
Hi @cmaumet - Here it's still truncated: http://nidm.nidash.org/specs/nidm-experiment_dev.html maybe the source image hasn't been pushed here http://nidm.nidash.org/specs/img/nidm-experiment-uml.png from github?

**Comment by cmaumet** [comment]
@nicholst: sorry this was not clear... I meant the html should have been re-generated in @nicholsn's branch (not pushed yet?) but to update the website at http://nidm.nidash.org, the usual procedure is still needed (cf. [Generate the NIDM website](https://github.com/incf-nidash/nidm/wiki/Generate-the-NIDM-Website)).

**Comment by nicholst** [comment]
Sorry!  I misread @nicholsn  as @nicholst.  Ignore me!

**Comment by nicholsn** [comment]
this was resolved at: http://nidm.nidash.org/specs/nidm-experiment_dev.html
