### ISSUE TITLE
Conversion from provn to turtle

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#254]
There are currently a number of pull requests (#248, #241, #252, #253) that do pass the tests when I start them locally from my machine but fail on Travis. 

The test suite fails with a timeout when accessing the ProvStore:

```
.INFO:TestProvStoreLinks:Test: TestProvStoreLinks
INFO:TestProvStoreLinks:    Prov store URL: https://provenance.ecs.soton.ac.uk/store/documents/31582.ttl
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

We are currently linking to the ProvStore in order to convert from ttl to provn (when using Travis. Locally this conversion is done with the java provToolbox). 

I can see two possible solutions to avoid querying the provStore to do the conversion:
1. Start using the python `prov` toolbox to convert from ttl to provn. @satra: do you think we could start beta testing the export on the python `prov` toolbox or shall we wait a bit more?
2. Use the java provToolbox. This would mean that we need to be able to install it as a dependency when starting the tests on Travis CI. I am not sure how to do this given that the rest of the project is in python. Would someone have an example of Travis CI configuration adding a dependency in another programming language?

Thanks in advance for any feedback/tip/comment.

**Comment by cmaumet** [comment]
I have just renamed this issue in "Conversion from provn to turtle". While there is no longer a timeout issue with the ProvStore (cf. #260), we still need to discuss how to handle the provn to turtle conversion in python.

**Comment by satra** [comment]
perhaps i can spend some time on this at the ohbm hackathon. i'll also see if i can get a summer urop to work on this.

**Comment by cmaumet** [comment]
@satra: that would be great! I think @jbpoline also had in mind that others in the NIDM group could contribute (this was in the agenda of the Washington NIDASH TF meeting if I remember correctly).

This is probably something we could discuss on one of the calls.

**Comment by cmaumet** [comment]
For info, the python NIDM-Results exporter now uses rdflib to export to turtle (cf. https://github.com/cmaumet/nidmresults/commit/d3ac863c568ac63cc78a430fa42f65474babb0fd). 

This avoids a dependency on the java provToolbox until the python prov toolbox can export to turtle.

**Comment by satra** [comment]
+1
