### ISSUE TITLE
Are T-Statistic Maps Used in Inference Activity

### ISSUE THREAD

**Issue by nicholsn** [incf-nidash/nidm#351]
I am working on a query discussed in [neurovault#354](https://github.com/NeuroVault/NeuroVault/pull/354#issuecomment-151973717) and can't seem to find a link between a t-statistic map and coordinates via an inference activity. Is it correct that t-stats don't have coordinates?

Using http://neurovault.org/collections/877/fsl_course_av.nidm.ttl as an example:

``` python
import rdflib
g = rdflib.Graph()
g.parse("./fsl_course_av.nidm.ttl", format='turtle')
tstat = """
    PREFIX nidm: <http://purl.org/nidash/nidm#> 
    PREFIX prov: <http://www.w3.org/ns/prov#> 
    PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
    SELECT DISTINCT ?tstatmap ?tstatmap_filename ?infer
    WHERE {?tstatmap nidm:NIDM_0000123 obo:STATO_0000176 ; # t-statistic
                     nfo:fileName ?tstatmap_filename .
           }"""
r = g.query(tstat)
print r.serialize(format='csv')
tstatmap,tstatmap_filename
http://iri.nidash.org/5cddab88-3087-4e36-a9d0-6d7698bd91aa,tstat2.nii.gz
http://iri.nidash.org/5cddab88-3087-4e36-a9d0-6d7698bd91aa,TStatistic_T002.nii.gz
http://iri.nidash.org/f4894d84-7359-46c6-a68b-99a3de869dcf,tstat1.nii.gz
http://iri.nidash.org/f4894d84-7359-46c6-a68b-99a3de869dcf,TStatistic_T001.nii.gz
```

But if I check for an inference node, as one might expect from http://nidm.nidash.org/specs/nidm-results_110.html#overview-1: 
``` python
inference_used_tstat = """
    PREFIX nidm: <http://purl.org/nidash/nidm#> 
    PREFIX prov: <http://www.w3.org/ns/prov#> 
    PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
    SELECT DISTINCT ?tstatmap ?tstatmap_filename ?inference
    WHERE {?tstatmap nidm:NIDM_0000123 obo:STATO_0000176 ; # t-statistic
                     nfo:fileName ?tstatmap_filename .
           ?inference prov:used ?tstatmap .
           }"""
r = g.query(inference_used_tstat)
print r.serialize(format='csv')
tstatmap,tstatmap_filename,inference
```
So is it that t-stats don't necessarily have coordinates?

**Comment by nicholst** [comment]
Thats right. I had to check the "Overview" figure in the specs, but that shows that t-stat images arise from contrast estimation and peaks subsequently arise from inference. So you should be able to make a query that captures the link between peaks & t-stat but it will be through the inference activity.

**Comment by nicholsn** [comment]
Right, but that doesn't seem to be the case since the connection between a
statmap and inference activity is through a `prov:used` relationship and
when added to my query there are no results. However, for z-stat maps there
are results with an inference activity added to the query. Any reason why
there wouldn't be peaks for a tstatmap?

sent via mobile, please excuse brevity and typos

**Comment by nicholst** [comment]
I perused the ttl file and I don't know why there's no trace of the T-stat map there. Our recently created examples our FSL ttl files have both Z and T stat images linked.  

For convenience:
* OpenfMRI study 1, subject 1, NIDM Results export as 

  * zip files: [FSL nidm all contrasts](http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/nidm/ds000001/results/sub01.feat.zip) | [SPM nidm contrast 1](http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/nidm/ds000001_sub01_nidm_001.zip)

  * directories:   [FSL nidm](http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/nidm/ds000001/results/sub01feat) | [SPM nidm contrast 1](http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/nidm/ds000001/results/sub01/nidm_001) 

(The other 6 contrasts for SPM can be obtained by incrementing the URL from 001 to 002, etc).

@vsoch  - Where did those NeuroVault NIDM examples come from?

**Comment by vsoch** [comment]
We have a "NIDM Showcase" collection in NeuroVault:

http://www.neurovault.org/collections/877/

@nicholst you might have some insight to the sparql query mystery that returns many equivalent coordinates for all different maps:

https://github.com/NeuroVault/NeuroVault/pull/354#issuecomment-152852493

The query is here:

https://github.com/vsoch/nidmviewer/blob/master/nidmviewer/sparql.py#L57

be careful, it looks like it might bite.

**Comment by vsoch** [comment]
And if you look at the images, some of them are named suggesting both T and Z statistic map. That might be where they went - dressing up for Halloween? :jack_o_lantern:

**Comment by vsoch** [comment]
Interesting - @nicholst are those zipped files nidm? I uploaded them to NeuroVault (my dev server) and they do not register as NIDM, they register just as "Other" generic maps.

**Comment by vsoch** [comment]
Maybe @chrisfilo can have a look?

**Comment by chrisfilo** [comment]
a) the examples from http://www.neurovault.org/collections/877/ come from
our tests. The data there was generated using nidmfsl run on FEAT folders
provided by the FSL course. I assume that because FSL does not produce T
maps only Z maps were present. Is this incorrect?

b) To make NeuroVault understand NIDM you have to use appropriate
extension: .nidm.zip. If you rename them they will be recognized.

I would like to make .nidm.zip a standard for exchanging those files. Could
we agree to use it when sharing zipped NIDM folders?

**Comment by vsoch** [comment]
That did the trick to fix the upload. the sub01 folder did not work with the viewer, suggesting a different version possibly. The ds000* folder did work, and there is one TStatistic map.

**Comment by jbpoline** [comment]
I had a look at both 
http://neurovault.org/collections/877/fsl_course_av.nidm/fsl_course_av.nidm.ttl
and
http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/nidm/ds000001/results/sub01feat/nidm.ttl 

Both files seem to contain both Z and T maps, and inference activities, so does anybody know why we get this difference between the two files ?

**Comment by cmaumet** [comment]
In FSL, when a T-test is computed, both a T-Statistic map and a Z-Statistic map are created. But it's the Z-Statistic map that is used to make inference. So, only the Z-Statistic map is used by the inference activity (in FSL). In SPM, the T-Statistic Map is used directly by the inference. 

The [peak query](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/query/peak.rq) can handle both cases. Does this help?

**Comment by jbpoline** [comment]
thanks Camille - that clarifies things !

**Comment by nicholsn** [comment]
Very much so, thanks Camille!

sent via mobile, please excuse brevity and typos
