### ISSUE TITLE
http://incf.org/ns/nidash/nidm resolves to nonexistent http://ns.nidash.org

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidm#353]
For no particular reason, I tried resolving the URI of a definition, e.g. http://purl.org/nidash/nidm#NIDM_0000127 (nidm_version).  This resolved to 

> https://raw.githubusercontent.com/incf-nidash/nidm/master/nidm/nidm.owl#NIDM_0000127

and that lists this as the ontology: 

> http://incf.org/ns/nidash/nidm

and _that_ resolves to

> http://ns.nidash.org

which is "404 - There isn't a GitHub Pages site here."

@nicholsn - I know it doesn't matter officially, but can http://ns.nidash.org be created and offer something useful (nidm.owl?)  Or should we change the redirect from INCF?

@jbpoline - As a side note, will the reorganization of the INCF funding, will "NIDASH" still exist as an entity?

**Comment by satra** [comment]
@nicholst - we just need to setup a static site for ns.nidash.org (on github).

**Comment by satra** [comment]
@nicholst - more importantly we need to decide where the purl resolves and how.

also we need to be able to provide the human readable version when asked by a human and the machine readable version when ask by a machine.

**Comment by satra** [comment]
also https://github.com/incf-nidash/nidm/blob/master/nidm/nidm.owl has not been updated.

**Comment by nicholsn** [comment]
Also the purl.org admin interface is currently down so I can't update the
purl 303 redirect but will once it is back up. See:
https://groups.google.com/forum/m/#!topic/persistenturls/ZPE8_udZwnY

Will also send a PR to update our top level owl file with more meaningful
info and imports - stll need to handle the issues satra mentions though...

sent via mobile, please excuse brevity and typos

also https://github.com/incf-nidash/nidm/blob/master/nidm/nidm.owl has not
been updated.

—
Reply to this email directly or view it on GitHub
<https://github.com/incf-nidash/nidm/issues/353#issuecomment-153374718>.

**Comment by jbpoline** [comment]
@nicholst : yes nidash will survive (unless we want it to stop).  
@nicholsn @satra @nicholst : I had done the experiment of trying to find for the relation between a term and it's definition and its unique identifier, which was not straightforward, and I had in mind for the nidm sprint to do the documentation / tool to make the link very easy. We should also keep in mind the larger nidm-terms project for this.

**Comment by khelm** [comment]
Yes, I'm working on the draft charter for the terms project today and I have in there the deployment of infrastructure for proposing and discussing terms using our github model, but also as we discussed earlier, ways to point to other sources of terms.

**Comment by satra** [comment]
@jbpoline - yes - longer term architecture should be discussed and implemented as part of terms. as a first pass all we need is for the purl to point back to the appropriate definition location.

**Comment by cmaumet** [comment]
I think this is now resolved. Please feel free to reopen this issue if you think this should be discussed further. Thanks!
