### ISSUE TITLE
Neurolex to scicrunch: impact on namespace and ids

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm#371]
NeuroLex is transitioning to https://scicrunch.org (cf. http://neurolex.org/wiki/Main_Page). 

We need to:
 - [x] check if this impacts the namespace. 
 - [x] decide if we want to use the new scicrunch identifiers or the original NeuroLex ids (e.g. for the [AFNI term](https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/dfb49edb-2855-57a5-93df-6c2bb267cfde/search?q=afni&l=), we have: `SCR_005927` versus `nif-0000-00259`)

**Comment by cmaumet** [comment]
@satra, @jbpoline: as discussed on Monday's call, I have created an issue to discuss namespace/ids for SciCruch: https://github.com/SciCrunch/NIF-Ontology/issues/31. It would be great if you can add up to the discussion over there following your meeting. Thank you in advance!

**Comment by jbpoline** [comment]
I saw that nif-0000-00259 is listed as "alternate" for SCR_005927
Do you have some thoughts on the pros / cons of switching or not switching and how costly switching will be at that stage?
will definitely talk about this ...

**Comment by cmaumet** [comment]
@jbpoline: yes exactly, the "alternate id" was one of my questions. In terms of pros and cons, if we switch now, it would mean that SPM and FSL software (the 2 NeuroLex terms we are currently using) would have different ids. This would break backward-compatibility with previous NIDM-Results documents. But according to https://github.com/SciCrunch/NIF-Ontology/issues/31, using the `SRC_***` ids is the recommended approach and at this stage of NIDM, I would be in favor for switching.

**Comment by jbpoline** [comment]
Ah, I see that we may have our answer already :) but will ping Jeff
tomorrow as well see if he has further thoughts
cheers
JB

**Comment by cmaumet** [comment]
Thank you!

**Comment by cmaumet** [comment]
This has been further discussed in https://github.com/SciCrunch/NIF-Ontology/issues/31. Updates were implemented in https://github.com/incf-nidash/nidm/pull/374.
