### ISSUE TITLE
FSL's Drift basis implementation off 

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidm#379]
This FSL bug is so minor and so deep, I don't see the point of raising it with FSL. (I.e. changing it would change every analysis, but with probably nominal effect).

The stated definition of the Feat "High pass filter cuttoff (s)" is advertised as per our [specs](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/terms/nidm-results.owl#L435):

```obo:IAO_0000115 "Full Width at Half Maximum in seconds of the Gaussian weight function used in the running line smoother." ;```

However, the implementation (FSL:fsl/tcl/featlib.tcl:L2072) uses a FWHM-to-Sigma conversion factor of 2.0 instead of 2.355:
```
        set hp_sigma_sec [ expr $fmri(paradigm_hp) / 2.0 ]
        set hp_sigma_vol [ expr $hp_sigma_sec / $fmri(tr) ]
```

This has been noted and reported by users (see [this JISCmail FSL thread](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1109&L=FSL&P=R30849); there Steve Smith is quoted as saying " there isn't actually much difference between 2 and 2.35.").

Anyway, I don't know whether we should just leave this as is, or note that the definition *really* should be

```obo:IAO_0000115 "Doubled standard deviation in seconds of the Gaussian weight function used in the running line smoother." ;```

**Comment by cmaumet** [comment]
Thank you @nicholst! The definition is updated as suggested in https://github.com/incf-nidash/nidm/pull/381.
