### ISSUE TITLE
icons connecting to github issues missing on rendered nidm results page

### ISSUE THREAD

**Issue by satra** [incf-nidash/nidm#383]
http://nidm.nidash.org/specs/nidm-results_120.html

**Comment by cmaumet** [comment]
Hi @satra! As the released versions are fixed, only the development version of the spec has links to create a new issue/see pending issues: http://nidm.nidash.org/specs/nidm-results_dev.html. 

Maybe we could add a statement at the beginning of the released spec to mention that comments should be made on the dev version?

**Comment by satra** [comment]
for pending issues i think it's fine to do it in the dev version. however, for the release version, i think people should still be able to submit an issue, and see the discussion about a term.

**Comment by satra** [comment]
so perhaps it would be good to have it on all versions.

**Comment by cmaumet** [comment]
> for pending issues i think it's fine to do it in the dev version. however, for the release version, i think people should still be able to submit an issue, and see the discussion about a term.

I agree. But could they use the dev version (that is basically a copy of the latest release plus ongoing changes) to view and start new comments? 

> so perhaps it would be good to have it on all versions.

If we open commenting on all versions, how do you envision dealing with comments on deprecated terms or outdated definitions that have already been updated?

**Comment by khelm** [comment]
When a term is released could we put a marker on that spot in the discussion thread to demarcate that all previous discussion was for the release version.  Any discussion after that would be for the next release.  

Is there a way to close discussions as I've seen on other websites?

**Comment by satra** [comment]
@cmaumet - they could use the dev version to start a new issue, but i'm trying to simplify the number of clicks and some principles. in any release, it would be good to link to the latest discussion for that version of the term. (it's like the provenance of the term). with respect to opening an issue, the issue could be either about a released term or the current dev term.

here is a potential solution:

- the dev version is always the default
- if the dev version changes from the prior release, we annotate that somehow (color, icon, pointer to previous version, etc.,.)
- in released versions we can indicate (via some javascript + rdflib.js) if the term has been modified since the release and point to the latest version of the term. i.e., we can think of the rendered html as dynamic on top of a static released owl file.

@khelm - one of the nice things about github is that you can very simply cross-link across discussions. so indeed we can close a discussion and even when a new discussion starts on the same term, we could point to the older discussion.

**Comment by cmaumet** [comment]
@satra: that would be nice! But would require more development effort than our current solution... Shall we discuss this further on the next call to see if someone has some resources to give it a go?

**Comment by satra** [comment]
sounds good. i may be able to ask someone to work on it.

**Comment by cmaumet** [comment]
I think we can close this issue. @satra: feel free to reopen it if you think this should be discussed further. Thanks!
