### ISSUE TITLE
Study vs Visit in NIDM-Experiment

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm#406]
I was speaking with Smruti about dealing with visits within NIDM-Experiment and we wanted some feedback from the group.  I have updated the ver7 lucidchart to reflect our thinking on this issue
[The chart is here ](https://www.lucidchart.com/invitations/accept/1c640f1e-d830-48b8-9ce0-dc1582e6ef8d)
One way to deal with this is that we treat Visit and Study as synonyms and we define a owl:DatatypeProperty with label "visit ID" that will link the Study Objects to a specific visit number.  A Study then is the collection of Data Acquisition Objects generated by Agents during Activities performed during a certain time duration (read:"Visit").  

Anyone have any comments, suggestions, or issues with this?

**Comment by nicholst** [comment]
Does BIDS offer any help/clarity here?  One BIDS parent directory corresponds to a 'study' as far as I can see, and then within that there is an option for Visits or Sessions, as documented here http://bids.neuroimaging.io/bids_spec1.0.1.pdf#page=29

Does that suggest that Visit and Study should be distinct?

**Comment by satra** [comment]
@nicholst - it's a little more complicated than bids, since we are talking of more general experiment logic here. for example, a session could be a purely behavioral session, or an online session, or a remote session in a participant's home - not just an imaging session.

going to @khelm comments and the comments in the other thread, we are thinking of projects and sessions as activities, not entities, since they typically have a start time and an end time, which entities do not have.

in our mind, a project/study starts and ends over time (if end time is missing, then it is still ongoing).
within this project/study there are activities (all kinds: imaging sessions, screening sessions, logical sessions).

a logical session, which is what bids refers to as a session is a logical grouping of activities. for example, a person may come back on two separate scan sessions to finish acquiring data prior to some treatment. although each activity would be a separate session they can be grouped together as a logical session via a query. a decision was taken in bids to simplify to a logical session, something we don't have to do in the experiment model.

within non-logical (or actual) sessions data are acquired and the outcome of this acquisition activity is an acquisition object. so a session can generate a demographics object, a clinical assessment object, or a imaging object.

there is a lot of overlap, at least at this conceptual level, with nidm workflow. since a project is a workflow after all.

**Comment by satra** [comment]
@khelm - with respect to this thread's title, my vote is to use the term `session` in lieu of `visit`.

**Comment by khelm** [comment]
I think this is a point-of-view issue and we need to think through the implications of choosing one versus the other (activity vs entity). @satra  from what you write above you seem to be viewing a Project and Study as activities that are collection of other activities.  The alternative view, and the one that I was operating under, is that a Project is a collection of Studies, which in turn contain Acquisition Objects .  

The reason I took the Object point-of-view was because I was looking at this in light of how one would query to find a particular Acquisition Object and it seems to me that being Object-centric would make that easier.  I think of Activities as ""an identifiable activity, which performs a piece of work." [PROV-DM]", more like Acquisition or Assessment than Study, which in it's noun sense seems to be what we are talking about here. It doesn't seem to me that the verb sense of Study is what we are talking about when I say that I'm looking for data from a particular "study" .  Even if you substitute "Session" for Study/Visit, that still seems to me to be the noun form and I don't see what knowing the start and end time gets you, since we usually store acquisition dates rather than start and end times (though I get that that is what prov allows you to do).

The other point is that I can see Study/Session being Activities - from the current definitions I see in Bioportal, but if Project is an Activity as well it's not clear to me how one connects Project -> Study using Prov properties.  What you have for Activity -> Activity properties is:
wasInformedBy or wasScheduledAfter. The former seems vague and the latter is not really the correct relation either.
The only thing that would be close is 
Activity -> hadRecipe - Recipe
and in that case the Study would be a recipe rather than an activity.

The other issue is one of vocabulary.  The hierarchy that I'm currently using is:
Project = collection of all Objects that are generated in the course of meeting a single requirement 
   -Study = collection of all Objects acquired from a subject during a finite period with a single acquisition modality 

If Workflows wants Session, rather than Study/Visit that's fine with me, but we still have to work out the entity/activity issue either way.  Also I was thinking of Session as being attached to a modality of data acquisition. So if a person had an MRI scan and then moved over to the MEG machine that those would be two separate Sessions.  This would help distinguish it from the MRI/PET case for example in which both types of data were acquired in the same...Session.

**Comment by satra** [comment]
@khelm - thank you. i do think this needs to be discussed.

what i was missing from the current (noun) formulation was the idea of a timeline. any project typically has a timeline and different pieces happen on that timeline, which imo fits quite well with the prov model. however, you are absolutely correct that prov doesn't have a direct relationship to indicate sub-activity. 

in provone, which we are using for workflow, there are two pieces: `Process` (Noun/Entity/Specification) and `ProcessExec` (Verb/Activity/Execution). coupled with these it has the relations, `hasSubProcess` (for the noun form) and `isPartOf` (for the verb form) respecitively. we are planning to use that currently for nidm-w. a long time back during the development of prov this came up, and the decision was to use `isPartOf` as relating a sub activity to a parent activity. prov also has `wasInformedBy`/`wasStartedBy`.

nidm-w doesn't have sessions. the idea of sessions comes from brainverse, which is currently much more closely related to nidm-e. and one can have specialization of sessions for different types of activities as you point out MRISession, MEGSession, PETMRISession, PETSession. i believe this also how xnat organizes things as well. as such a session generates entities (dicom objects, other files). one could consider an analysis session. 

re: queries on the graph, a few notes:

- all activities and entities will be associated, attributed to an individual who is a participant/sample. as such the queries. 
- we can always augment the graph with collections of entities and agents who are part of a project/study/investigation. (for example, we may generate a bids query, one that converts nidm-e graphs to a bids hierarchy)
- similar issues came up in nidm-workflow and we decided to separate the basic model with queries that augment the model, so we limited the collections.

here are some questions to further guide the discussion:

- in an ongoing project, would you be generating new collections, or adding to a collection in the current model? if adding, would you regenerate a new collection id with the added items? and would you invalidate the previous collection?
- logical via query vs actual being closer to time of events. one way to think about collections is to generate objects via queries, while the underlying model is closer to how real-world activities take place.
- one can also think of the logical aggregation as the noun form, while the realworld modeling is more in line with prov's verb form.
- perhaps we can represent some partial studies using nidm-e using these two approaches and write queries to see how things can be done.
- i think of queries and ontologies carrying the overhead of logic not the base data model. the advantage of the rdf/graph model is that we can refocus anytime (e.g., from participants to investigators).

**Comment by jbpoline** [comment]
Hi,

Quick question on: "... ontologies carrying the overhead of logic not the
base data model" :

Is the base data model usable/interpretable without the associated ontology?

cheers
JB

**Comment by satra** [comment]
@jbpoline - should have been more careful with that statement. i was trying to distinguish a scale of complexity in ontologies and that the base data model is still a graph. 

the base data model can be usable without the associated ontology in many cases, simply thinking of it as an extension from key-value representations to node-rel-node representation. also, if you consider the kinds of ontologies we are using they are graphs as well (i.e. we are not using many components of OWL that extend to reasoning).

**Comment by jbpoline** [comment]
Hi,

It might be interesting to list the use cases that need the ontology and
those that don't

cheers
JB
