### ISSUE TITLE
Remove "Stimulus File" and unneeded  SciCrunch terms

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm#441]
W have both "Stimulus File" and "Stimulus Presentation File". Remove "Stimulus File" and add "Stimulus Response File" to Auxiliary Files.  

"Stimulus File" and "Model Designer" are both from http://www.co-ode.org/ontologies/ont.owl
I will remove both since, with the removal of "Stimulus File" we only have a single term imported from that ontology.  I will make a new `nidm:ModelDesigner` term.

Also remove SciCrunch terms "FSL" and "SPM" which are SCR_002823 and SCR_007037.  These are already in NIDM-Results so they are unneeded here.
EX:  http://scicrunch.org/resolver/SCR_002823 which were subclasses of SIO_000097 ("software
 entity")

**Comment by tiborauer** [comment]
Should not we rather use SciCrunch in NIDM-Results, too?

**Comment by khelm** [comment]
Actually, I thought "FSL" and "SPM" were in Results, but I just looked at the latest nidm-results.owl file and I don't seem them. @cmaumet are they somewhere else or not there at all?  I searched for:
`label "SPM`
